apiVersion: v1
kind: ConfigMap
metadata:
  name: chg-2026-0059-control-plane
data:
  changeNumber: CHG-2026-0059
  applicationName: demo-go-color-app
  targetEnvironment: dev
  managedBy: devops-control-plane
